-- 코드를 작성해주세요
# SELECT ID, IF(SIZE_OF_COLONY>1000,'HIGH',IF(SIZE_OF_COLONY>100,'MEDIUM','LOW')) AS SIZE
# FROM ECOLI_DATA

SELECT ID,
    CASE 
        WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH'
        WHEN SIZE_OF_COLONY > 100 THEN 'MEDIUM'
        ELSE 'LOW'
    END SIZE
FROM ECOLI_DATA
ORDER BY ID